include: package:lints/recommended.yaml
analyzer:
  exclude: [lib/generated/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    invalid_assignment: warning
    missing_return: error

linter:
  rules:
    - always_declare_return_types
    - public_member_api_docs
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - prefer_final_in_for_each
    - prefer_single_quotes
    - await_only_futures
    - always_use_package_imports
    - avoid_print
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_type_to_string
    - invariant_booleans
    - no_adjacent_strings_in_list
    - throw_in_finally
    - unnecessary_statements
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_returning_null
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cast_nullable_to_non_nullable
    - directives_ordering
    - do_not_use_environment
    - empty_catches
    - eol_at_end_of_file
    - join_return_with_assignment
    - no_default_cases
    - no_runtimeType_toString
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - prefer_asserts_with_message
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_null_aware_method_calls
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_const
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_string_buffers
    - sort_pub_dependencies
