name: keyboard_service
description: Keyboard visibility / (auto-) dismiss package without the need of native plugin
version: 2.0.3
homepage: https://github.com/Gerrel/keyboard_service

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
